### ISSUE TITLE
EditorXR not working in Unity 2017.2.3p1

### ISSUE THREAD

**Issue by crawelsky** [Unity-Technologies/EditorXR#476]
Hi,

I'm trying to use the EditorXR with Unity 2017.2.3p1 everything was well until I launch it with Ctrl+E. I'm just able to see the controllers and some tool tips nothing else. Is someone has any idea ?

Thanks !

**Comment by amirebrahimi** [comment]
Can you take a screenshot? Usually that is all you see until you launch a tool.

**Comment by crawelsky** [comment]
Hi, 
Thanks for you quick answer. Here is the screenshot ! As you can the EditorXR is running but currently all the controllers don't do anything. 

![editorxr](https://user-images.githubusercontent.com/6507345/41946580-627a0d2e-79f2-11e8-99d3-17573c339fb9.PNG)

**Comment by amirebrahimi** [comment]
Hmm...It looks like your headset isn't tracking. Are you able to see anything in your headset? Have you enabled VR in the player settings? Is this Vive or Oculus? Does it work in play mode?

**Comment by crawelsky** [comment]
Hi,  I checked Steam VR and everything seems ok. Am able to see the same thing as in the picture. And only OpenVR is enable in the player settings. It is a Vive and the game itself work very well in play mode. Something odd happen, when I try to use EditorXR in the SteamVR example scene I get the last picture I show to you. But in my own scene where I use VRTK it doesn't work.

**Comment by amirebrahimi** [comment]
Can you try a completely empty project with EditorXR? Also, how did you install EditorXR - from a unity package or pulling from github?

**Comment by crawelsky** [comment]
Hi, for the first time I installed EXR with the Unity package. But now I made a new empty project and install EXR with git clone request for developer following the instructions on the EXR page but I have the same issue.

**Comment by amirebrahimi** [comment]
This might be easier to resolve over a quick Hangouts / Skype. Can you send me an email to amir at unity3d.com and some days/times that work for you.

**Comment by amirebrahimi** [comment]
Glad we got to chat @crawelsky. I just tested this on 2017.3.1f1, which wasn't working for you and it works for me. I had to turn on the UI layer, so I could see the UI, but the button presses work. So, unfortunately, I'm still at a loss to know what is going wrong with your machine. Do you have any other machines you can test with? Any other Vive controllers? Do you have any other USB controllers hooked up to your machine?

Perhaps you can run System Info and export a copy and email it to me, so I can review. FYI - I'll be unable to test again for two weeks because I'll be out of the office and won't have a VR headset with me.

**Comment by crawelsky** [comment]
Hi, thanks you for your availability and you patience. I just tested the EXR on another machine with 2017.3.1f1 and everything works well. I still don't know what's the issue with this computer. But at least I know that the issue come from the computer then I can continue my work on the other computer. I put the system info in the attachment, I hope that will help to figure out the issue.

Thanks !
[sysInfo.txt](https://github.com/Unity-Technologies/EditorXR/files/2221542/sysInfo.txt)

**Comment by amirebrahimi** [comment]
If you're still wanting to fix that computer, my intuition is that it is related to the USB drivers, since your headset was tracking correctly and it was only the controllers that weren't working. Can you try this and let me know?
https://www.drivethelife.com/windows-drivers/htc-vive-usb-errors-and-troubleshooting.html

Otherwise, if you're okay using the other computer, then we can close this issue.

**Comment by amirebrahimi** [comment]
I looked through your sysinfo.txt file and although your graphics card is an older model (GTX 770) and that your WIDCOMM USB Bluetooth driver is listed as running in "Degraded" mode, which was odd to me.

**Comment by crawelsky** [comment]
Hi, thanks you for you feedback and propositions. I tried the all the solution proposed on the website that you gave me but I still got the same problem on that computer. When I checked the Sysinfo.txt there are several service  running in degraded mode, I don't know why it's like that and how to fix it. I'll work on the other computer. Thanks for you help. I think we can close the issue.
