### ISSUE TITLE
 'Range' is an ambiguous reference between 'Assets.Utilities.Range' and 'System.Range'

### ISSUE THREAD

**Issue by Forux** [Unity-Technologies/EditorXR#579]
Right after installing to the newly created empty 3D project in the latest Unity3D version 2021.2.4f1 got this error

```
Library\PackageCache\com.unity.editorxr@0.4.12-preview\Runtime\libs\input-prototype\Input\Core.Extensions\JoystickControlMapping.cs(12,10): error CS0104: 'Range' is an ambiguous reference between 'Assets.Utilities.Range' and 'System.Range'

Library\PackageCache\com.unity.editorxr@0.4.12-preview\Runtime\libs\input-prototype\Input\Core.Extensions\JoystickControlMapping.cs(13,10): error CS0104: 'Range' is an ambiguous reference between 'Assets.Utilities.Range' and 'System.Range'

Library\PackageCache\com.unity.editorxr@0.4.12-preview\Runtime\libs\input-prototype\Input\Core.Extensions\JoystickControlMapping.cs(14,10): error CS0104: 'Range' is an ambiguous reference between 'Assets.Utilities.Range' and 'System.Range'
```

**Comment by mtschoen-unity** [comment]
Hi there! Thanks for reporting this issue. I pushed a fix since it was pretty straightforward, but I should warn you that you won't be able to take full advantage of EditorXR in this version of Unity. We no longer support this product and the edit mode functionality relies on legacy VR support, which was deprecated in 2020. If you intend to use EditorXR in play mode or Player builds, hopefully this will unblock you.
